name: string-cpp-testing

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: build
        run: |
          clang++ -std=c++20 -gdwarf-4 -O0 -Wall -Wextra -Werror -o ./test_simple src/string.h src/string.cpp
          clang++ -std=c++20 -O2 -Wall -Wextra -Werror -o ./test_simple_opt src/string.h src/string.cpp
          clang++ -std=c++20 -g -O0 -Wall -Wextra -Werror -fsanitize=undefined -o src/string.h src/string.cpp

      - name: simple test
        run: ./test_simple
      - name: simple optimized test
        run: ./test_simple_opt
      - name: ubsan test
        run: ./test_ubsan
